{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "final-task.fullname" . }}
  labels:
    {{- include "final-task.labels" . | nindent 4 }}
{{- end }}
